schema_controller:
  resource: ../src/JsonSchema/
  type: annotation

identity_user_controller:
  resource: ../src/BoundedContext/Identity/User/Controller/
  type: annotation

security_session_controller:
  resource: ../src/BoundedContext/Security/Session/Controller/
  type: annotation